name: CI

on:
  push:
    branches: [ master, GPU-3D-unmanaged ]
    paths:
      - '**.f90'
      - '**.fpp'
      - '**.sh'
      - '**.py'
      - '**.yaml'
      - '**.yml'
      - 'Makefile'
      - 'makefile'

  pull_request:
    branches: [ master, GPU-3D-unmanaged ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - c:  regular 
            os: ubuntu-20.04
            cc: release-cpu
          - c:  nvidia
            os: ubuntu-20.04
            cc: release-gpu

    steps:
      - name: Fetch (Aptitude) Dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y tar wget make cmake gcc g++ python3 openmpi-* python python-dev python3-dev python3-venv libopenmpi-dev
          pip3 install pyyaml colorama fypp

      - name: Install Nvidia HPC SDK
        if: contains(matrix.c, 'nvidia')
        run: |
          echo 'deb [trusted=yes] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list
          sudo apt-get update  -y
          sudo apt-get install -y nvhpc-22-2

      - name: Clone MFC
        uses: actions/checkout@v2

      - name: Build MFC and its dependencies (mfc.py)
        run: |
          chmod +x ./mfc.sh
          ./mfc.sh --build -cc ${{ matrix.cc }} -j $(nproc)

      - name: Run MFC Tests
        run: ./mfc.sh --test

      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Ubuntu-logs
          path: |
            build/**/*.log
            tests/**/*.dat
            tests/**/*.out
            tests/**/*.inp

