name: CI

on:
  push:
    branches: [ master, GPU-3D-unmanaged ]
    paths:
      - '**.f90'
      - '**.fpp'
      - '**.sh'
      - '**.py'
      - '**.yaml'
      - '**.yml'
      - 'golden.txt'
      - 'Makefile'
      - 'makefile'

  pull_request:
    branches: [ master, GPU-3D-unmanaged ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Clone MFC
        uses: actions/checkout@v2

      - name: Install (Aptitude) Package
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y tar wget make cmake gcc g++ python3 openmpi-* python python-dev python3-dev python3-venv libopenmpi-dev
      # 
      - name: Install Nvidia HPC SDK
        run: | # per https://docs.nvidia.com/hpc-sdk/hpc-sdk-install-guide/index.html#install-linux-end-usr-env-settings
          echo 'deb [trusted=yes] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list
          sudo apt-get update  -y
          sudo apt-get install -y nvhpc-22-2
          NVARCH=`uname -s`_`uname -m`; export NVARCH
          NVCOMPILERS=/opt/nvidia/hpc_sdk; export NVCOMPILERS
          MANPATH=$MANPATH:$NVCOMPILERS/$NVARCH/22.2/compilers/man; export MANPATH
          PATH=$NVCOMPILERS/$NVARCH/22.2/compilers/bin:$PATH; export PATH
          export PATH=$NVCOMPILERS/$NVARCH/22.2/comm_libs/mpi/bin:$PATH
          export MANPATH=$MANPATH:$NVCOMPILERS/$NVARCH/22.2/comm_libs/mpi/man
          export CUDA_HOME=/opt/nvidia/hpc_sdk/Linux_x86_64/22.1/cuda/
          export CUDA_DIR=$CUDA_HOME

      - name: Install Pip Dependencies
        run: |
          pip3 install pyyaml colorama fypp

      - name: Build MFC and its dependencies
        run: |
          chmod +x ./mfc.sh
          ./mfc.sh build -cc release-cpu -j $(nproc)
          ./mfc.sh build -cc release-gpu -j $(nproc)

      - name: Test MFC
        run: |
          ./mfc.sh test -cc release-cpu
          ./mfc.sh test -cc release-gpu
      
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ matrix.os }}
          path: |
            build/**/*.log
            tests/**/*.dat
            tests/**/*.out
            tests/**/*.inp
            tests/**/*.txt
            tests/*.txt
